apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: {{ .Values.services.admin.replicas }}
  selector:
    matchLabels:
      app: admin
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: {{ .Values.services.admin.image }}:{{ .Values.services.admin.tag }}
          ports:
            - containerPort: {{ .Values.services.admin.port }}
          envFrom:
            - configMapRef:
                name: streamingapp-config
            - secretRef:
                name: streamingapp-secret
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.admin.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.admin.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: admin-svc
spec:
  selector:
    app: admin
  ports:
    - port: {{ .Values.services.admin.port }}
      targetPort: {{ .Values.services.admin.port }}
